export const GET_ARTICLES_POCKET = "GET_ARTICLES_POCKET";
export const UPDATE_USERNAME = "UPDATE_USERNAME";
export const GET_ARTICLES_TO_TAG = "GET_ARTICLES_TO_TAG";
export const TAGGING_COMPLETE = "TAGGING_COMPLETE";
